


all_cities = {
    # All EST Time Cities
    "New York": "US/Eastern",
    "Boston": "US/Eastern",
    "Philadelphia": "US/Eastern",
    "Miami": "US/Eastern",
    "Atlanta": "US/Eastern",
    "Chicago": "US/Eastern",
    "Detroit": "US/Eastern",
    "Indianapolis": "US/Eastern",
    "Charlotte": "US/Eastern",
    "Washington D.C.": "US/Eastern",
    "Toronto": "US/Eastern",
    "Montreal": "US/Eastern",
    "Ottawa": "US/Eastern",
    "Pittsburgh": "US/Eastern",
    "Cleveland": "US/Eastern",
    "Buffalo": "US/Eastern",
    "Rochester": "US/Eastern",
    "Syracuse": "US/Eastern",
    "Baltimore": "US/Eastern",
    "Richmond": "US/Eastern",
    "Norfolk": "US/Eastern",
    "Raleigh": "US/Eastern",
    "Charleston": "US/Eastern",
    "Jacksonville": "US/Eastern",
    "Tampa": "US/Eastern",
    "Orlando": "US/Eastern",
    "Fort Lauderdale": "US/Eastern",
    "West Palm Beach": "US/Eastern",
    
    # All CST Time Cities
    'Chicago': 'US/Central',
    'Dallas': 'US/Central',
    "Arlington" : "US/Central",
    'Houston': 'US/Central',
    'Kansas City': 'US/Central',
    'Minneapolis': 'US/Central',
    'New Orleans': 'US/Central',
    'Oklahoma City': 'US/Central',
    'St. Louis': 'US/Central',
    'Wichita': 'US/Central',
    
    
    # All MST Time Cities
    'Billings' : "US/Mountain",
    'Bozeman' : "US/Mountain",
    'Butte' : "US/Mountain",
    'Helena' : "US/Mountain",
    'Kalispell' : "US/Mountain",
    'Missoula' : "US/Mountain",
    'Cheyenne' : "US/Mountain",
    'Casper' : "US/Mountain",
    'Laramie' : "US/Mountain",
    'Rock Springs' : "US/Mountain",
    'Sheridan' : "US/Mountain",
    'Gillette' : "US/Mountain",
    'Denver' : "US/Mountain",
    'Colorado Springs' : "US/Mountain",
    'Aurora' : "US/Mountain",
    'Fort Collins' : "US/Mountain",
    'Lakewood' : "US/Mountain",
    'Thornton' : "US/Mountain",
    'Phoenix' : "US/Mountain",
    'Tucson' : "US/Mountain",
    'Mesa' : "US/Mountain",
    'Chandler' : "US/Mountain",
    'Glendale' : "US/Mountain",
    'Scottsdale' : "US/Mountain",
    'Albuquerque' : "US/Mountain",
    'Las Cruces' : "US/Mountain",
    'Rio Rancho' : "US/Mountain",
    'Santa Fe' : "US/Mountain",
    'Roswell' : "US/Mountain",
    'Farmington' : "US/Mountain",
    'Salt Lake City' : "US/Mountain",
    'West Valley City' : "US/Mountain",
    'Provo' : "US/Mountain",
    'West Jordan' : "US/Mountain",
    'Orem' : "US/Mountain",
    'Sandy' : "US/Mountain",
    
    
    # All PST Time Cities
    'Portland' : "US/Pacific",
    'Eugene' : "US/Pacific",
    'Salem' : "US/Pacific",
    'Gresham' : "US/Pacific",
    'Hillsboro' : "US/Pacific",
    'Beaverton' : "US/Pacific",
    'Seattle' : "US/Pacific",
    'Spokane' : "US/Pacific",
    'Tacoma' : "US/Pacific",
    'Vancouver' : "US/Pacific",
    'Bellevue' : "US/Pacific",
    'Everett' : "US/Pacific",
    'Los Angeles' : "US/Pacific",
    'San Diego' : "US/Pacific",
    'San Jose' : "US/Pacific",
    'San Francisco' : "US/Pacific",
    'Fresno' : "US/Pacific",
    'Sacramento' : "US/Pacific",
    'Las Vegas' : "US/Pacific",
    'Reno' : "US/Pacific",
    'Henderson' : "US/Pacific",
    'Sparks' : "US/Pacific",
    'Carson City' : "US/Pacific",
    
    
    # All Australian timezone
    "Brisbane": "Australia/Brisbane", #
    "Adelaide": "Australia/Adelaide", #
    "Hobart": "Australia/Hobart", #
    "Melbourne": "Australia/Melbourne", #
    

    "Darwin": "Australia/Darwin", #
    "Sydney" : "Australia/Sydney", #
    "Newcastle" : "Australia/Sydney",
    "Perth" : "Australia/Perth",
    "Gold Coast" : "Australia/Brisbane",
    "Launceston" : "Australia/Adelaide",
    

    
    # all european countries
    'AL': 'Europe',
    'AD': 'Europe',
    'AT': 'Europe',
    'BY': 'Europe',
    'BE': 'Europe',
    'BA': 'Europe',
    'BG': 'Europe',
    'HR': 'Europe',
    'CY': 'Europe',
    'CZ': 'Europe',
    'DK': 'Europe',
    'EE': 'Europe',
    'FO': 'Europe',
    'FI': 'Europe',
    'FR': 'Europe',
    'DE': 'Europe',
    'GR': 'Europe',
    'HU': 'Europe',
    'IS': 'Europe',
    'IE': 'Europe',
    'IT': 'Europe',
    'LV': 'Europe',
    'LI': 'Europe',
    'LT': 'Europe',
    'LU': 'Europe',
    'MK': 'Europe',
    'MT': 'Europe',
    'MD': 'Europe',
    'MC': 'Europe',
    'ME': 'Europe',
    'NL': 'Europe',
    'NO': 'Europe',
    'PL': 'Europe',
    'PT': 'Europe',
    'RO': 'Europe',
    'RU': 'Europe',
    'SM': 'Europe',
    'RS': 'Europe',
    'SK': 'Europe',
    'SI': 'Europe',
    'ES': 'Europe',
    'SE': 'Europe',
    'CH': 'Europe',
    'UA': 'Europe',
    'GB': 'Europe',
    'VA': 'Europe'
    
}